// Generated by bpmn-to-code
@file:Suppress("unused")

package io.miragon.blueprint.adapter.process

import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

/**
 * Job worker task types used in `@JobWorker(type = ServiceTasks.X)` annotations.
 * Kept as `const val String` because annotation arguments must be compile-time constants.
 */
object ServiceTasks {
  const val ACTIVATE_LEASING: String = "activateLeasing"

  const val BOOK_COSTS: String = "bookCosts"

  const val CANCEL_CONTRACT: String = "cancelContract"

  const val CANCEL_POLICY: String = "cancelPolicy"

  const val ISSUE_INSURANCE_POLICY: String = "issueInsurancePolicy"

  const val ORDER_BIKE: String = "orderBike"

  const val REQUEST_CANCELLATION: String = "requestCancellation"

  const val SEND_CANCELLATION_CONFIRMATION: String = "sendCancellationConfirmation"

  const val SEND_CONTRACT: String = "sendContract"

  const val SEND_REJECTION: String = "sendRejection"

  const val SEND_REMINDER_MAIL: String = "sendReminderMail"

  val all: List<String> = listOf(
    ACTIVATE_LEASING,
    BOOK_COSTS,
    CANCEL_CONTRACT,
    CANCEL_POLICY,
    ISSUE_INSURANCE_POLICY,
    ORDER_BIKE,
    REQUEST_CANCELLATION,
    SEND_CANCELLATION_CONFIRMATION,
    SEND_CONTRACT,
    SEND_REJECTION,
    SEND_REMINDER_MAIL,
  )
}
