// Generated by bpmn-to-code
package io.miragon.blueprint.adapter.process;

import java.util.List;

/**
 * Job worker task types used in {@code @JobWorker(type = ServiceTasks.X)} annotations.
 * Kept as {@code public static final String} because annotation arguments must be compile-time constants.
 */
public final class ServiceTasks {
  public static final String ACTIVATE_LEASING = "activateLeasing";

  public static final String BOOK_COSTS = "bookCosts";

  public static final String CANCEL_CONTRACT = "cancelContract";

  public static final String CANCEL_POLICY = "cancelPolicy";

  public static final String ISSUE_INSURANCE_POLICY = "issueInsurancePolicy";

  public static final String ORDER_BIKE = "orderBike";

  public static final String REQUEST_CANCELLATION = "requestCancellation";

  public static final String SEND_CANCELLATION_CONFIRMATION = "sendCancellationConfirmation";

  public static final String SEND_CONTRACT = "sendContract";

  public static final String SEND_REJECTION = "sendRejection";

  public static final String SEND_REMINDER_MAIL = "sendReminderMail";

  public static final String VALIDATE_APPLICATION = "validateApplication";

  private ServiceTasks() {
  }

  public static List<String> all() {
    return List.of(
        ACTIVATE_LEASING,
        BOOK_COSTS,
        CANCEL_CONTRACT,
        CANCEL_POLICY,
        ISSUE_INSURANCE_POLICY,
        ORDER_BIKE,
        REQUEST_CANCELLATION,
        SEND_CANCELLATION_CONFIRMATION,
        SEND_CONTRACT,
        SEND_REJECTION,
        SEND_REMINDER_MAIL,
        VALIDATE_APPLICATION);
  }
}
